### PR TITLE
Add missing source files referenced by PDB.

### PR DESCRIPTION
**Pull request by tom-englert**
Fix for https://github.com/NuGet/Home/issues/304

### CODE REVIEW

**Comment by yishaigalatzer** [comment]
Sweet, thanks for sticking through this long process! We will take a look

CC @tmat

**Comment by yishaigalatzer** [comment]
@tom-englert Can you please add a test case ?

**Comment by tom-englert** [comment]
@yishaigalatzer this is just wrapping existing stuff that is already unit tested (it does not make sense unit-testing DisSymReader here). I'm not the friend of adding dummy unit tests just for the sake of having a unit test.
This would need some integration test, but I see no framework for this.

**Comment by yishaigalatzer** [comment]
Completely agree. Command line tests in nuget.client repo are where the integration tests live.

Yishai

**Comment by yishaigalatzer** [comment]
@tmat - When do you plan to turn the RC into RTM?
@tom-englert - This need to go into the 2.10 branch rather than 2.9 branch

**Comment by tmat** [comment]
Within a week or so.

**Comment by tom-englert** [comment]
replaced with #23 based on 2.10 branch

**Pull request closed without merging**
